### ISSUE TITLE
[Bug] Heartbeat Crashes on Ditto SDK >= 4.8.0

### ISSUE THREAD

**Issue by rajramsaroop** [getditto/DittoAndroidTools#133]
Due to an update where a 3rd nullable parameter was added to the `upsert()` function of `DittoCollection` in version 4.8.0 of the SDK Heartbeat will crash with the following exception:

```
java.lang.NoSuchMethodError: No static method upsert$default(Llive/ditto/DittoCollection;Ljava/lang/Object;Llive/ditto/DittoWriteStrategy;ILjava/lang/Object;)Llive/ditto/DittoDocumentId; in class Llive/ditto/DittoCollection; or its super classes (declaration of 'live.ditto.DittoCollection' appears in /data/app/~~EMoNiiTI9LFLDaT0gVkzzg==/live.ditto.dittotoolsapp-fGINdgOqGsojyha8VWaMYg==/base.apk!classes2.dex)
at live.ditto.dittoheartbeat.HeartbeatKt.addToCollection(Heartbeat.kt:100)
at live.ditto.dittoheartbeat.HeartbeatKt$startHeartbeat$1.invokeSuspend(Heartbeat.kt:74)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:233)
at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:595)
at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7924)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e7a2, Dispatchers.Main]
```

## Steps to reproduce

1. In the `app` module point to the local version of `:DittoToolsViewer`
2. Update the Ditto version to any SDK version >= 4.8.0 in the version catalog
3. You may need to comment out some code in `DittoToolsViewer.kt` relating to the `HealthScreen()` [not relevant to this test] to get it to run
4. Load the app and tap on Heartbeat

## Expected behavior
We should see Heartbeat info

## Actual behavior
The app crashes with the above  exception

## Proposed Solution
We should wait for a fix from the SDK and then update the Ditto SDK to point to that version. This would also meant change the minimum version required for the heartbeat tool from 4.5.0 to whatever the fixed version is. (Other tools may remain at 4.5.0 as the minimum to keep compatibility)

**Comment by rajramsaroop** [comment]
Heartbeat tool has been updated to use a workaround which is just adding argument labels to the `upsert()` function.

Since this fixes the issue and does not introduce any tech debt I'm also going to close the issue.
